name: Securitydeep Scan

on: [push, workflow_dispatch]

jobs:
  scan_job:
    runs-on: ubuntu-latest
    name: Testing foss scanner
    steps:
      - name: Foss Scan
        uses: docker://saurabhthatte/foss-scan:v2
